@startuml
Admin o-> System: натискає кнопку “Обрати користувача”
System -> Admin:надсилає список зареєстрованих користувачів
Admin -> System:обирає зареєстрованого користувача із списку
System -> Admin:надсилає список dataset
Admin -> System:обирає необхідний dataset
System ->Admin:надсилає список прав
Admin ->Admin:обирає необхідні права
Admin ->System: натискає кнопку "Зберегти"
System -> Admin:повідомляє про надання прав зареєстрованому користувачу
@enduml