@startuml
User o-> System:  натискає кнопку “Реєстрація”
System -> User: надсилає йому форму для реєєстації
User -> User: заповнює форму
User -> System: натискає кнопку “Зареєструватись”
System -> User : надсилає повідомлення на електронну пошту повідомлення із кодом підтвердження
System -> User: надає форму для введення коду
User -> System: вводить код для підтвердження та натискає кнопку “Підтвердити”
System ->o User: повідомляє про успішну реєстрацію
@enduml