version: '3.6'

services:

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: data_management_system
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - 3358:3306
    container_name: micha_db_server